[package]
name = 'RS'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ['staticlib']
name = 'RS'

[dependencies]
extendr-api = { version = "0.8.0", features = ['non-api', 'result_condition'] }
mimalloc = "0.1.46"
# [target.'cfg(not(target_env = "msvc"))'.dependencies]
# tikv-jemallocator = "0.5"

[profile.release]
debug = true
lto = "fat"
opt-level = 3
incremental = false
codegen-units = 1
