[package]
name = 'containers'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ['staticlib']
name = 'containers'

[dependencies]
extendr-api = { version = "*", features = ['non-api'] }

[profile.release]
lto = "fat"
opt-level = 3
incremental = false
codegen-units = 1
