# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_RS_wrappers", use_symbols = TRUE, package_name = "RS")

#' @usage NULL
#' @useDynLib RS, .registration = TRUE
NULL

ClassDefinition <- new.env(parent = emptyenv())

ClassDefinition$name <- function() .Call(wrap__ClassDefinition__name, self)

ClassDefinition$new <- function(name, methods) .Call(wrap__ClassDefinition__new, name, methods)

ClassDefinition$print <- function() invisible(.Call(wrap__ClassDefinition__print, self))

ClassDefinition$get <- function(key) .Call(wrap__ClassDefinition__get, self, key)

#' @export
`$.ClassDefinition` <- function (self, name) { func <- ClassDefinition[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ClassDefinition` <- `$.ClassDefinition`

ClassInstance <- new.env(parent = emptyenv())

ClassInstance$new <- function(name, fields, def) .Call(wrap__ClassInstance__new, name, fields, def)

ClassInstance$print <- function() invisible(.Call(wrap__ClassInstance__print, self))

ClassInstance$get <- function(key) .Call(wrap__ClassInstance__get, self, key)

ClassInstance$set <- function(key, value) .Call(wrap__ClassInstance__set, self, key, value)

#' @export
`$.ClassInstance` <- function (self, name) { func <- ClassInstance[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ClassInstance` <- `$.ClassInstance`


# nolint end
